
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/peakyblinders
    username: postgres
    password: 261172
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
token:
  life-time-hours: 24